### ISSUE TITLE
mouse over to identify read identifier or list of identifiers

### ISSUE THREAD

**Issue by methylnick** [bjpop/methpat#22]
Is it possible to extract read identifier(s) associated with a particular pattern by having it displayed (and if possible saved or output somewhere) when one mouse over a particular pattern in the plot. 

This would enable extraction of the sequence read to determine bisulfite conversion efficiency.

**Comment by bjpop** [comment]
This has been (somewhat) addressed in 681d839bb85130be69b8d5f531c609c3014de5d0

Instead of a mouseover methpat can dump a file containing all the read IDs for each amplicon pattern.

This may be sufficient, or at least provide a stop-gap measure until a better solution is found.

**Comment by bjpop** [comment]
The current solution seems to be sufficient for the requirement. Closing the ticket.
